### ISSUE TITLE
undefined method `_run' on Ruby 1.9.2

### ISSUE THREAD

**Issue by btm** [chef/minitest-chef-handler#3]
Minitest::Chef::Handler will raise an exception on Ruby 1.9.2 because it calls _run when the version of Minitest included instead has a 'run' method.

```
[Tue, 10 Apr 2012 14:29:57 +0000] ERROR: Report handler MiniTest::Chef::Handler raised #<NoMethodError: undefined method `_run' for #<MiniTest::Chef::Runner:0x8fa06c4>>
```

Changing this call to 'run' works on Ruby 1.9.2-p318 but then fails on 1.8.7-p358 and 1.9.3-p125 with:

```
[Tue, 10 Apr 2012 14:56:00 +0000] ERROR: Report handler MiniTest::Chef::Handler raised #<ArgumentError: wrong number of arguments (0 for 1)>
```

Additional information can be found here: https://github.com/btm/minitest-handler-cookbook/issues/1
